// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FacturacionAPI_EF.Models;

public partial class Article
{
    public int IdArticulo { get; set; }

    public string Nombre { get; set; }

    public int PreUnitario { get; set; }

    public bool EstaActivo { get; set; }

    public virtual ICollection<BudgetDetail> DetallesFacturas { get; set; } = new List<BudgetDetail>();
}