// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FacturacionAPI_EF.Models;

public partial class BudgetDetail
{
    public int IdDetalle { get; set; }

    public int IdFactura { get; set; }

    public int IdArticulo { get; set; }

    public int Cantidad { get; set; }

    public virtual Article IdArticuloNavigation { get; set; }

    public virtual Budget IdFacturaNavigation { get; set; }
}