// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FacturacionAPI_EF.Models;

public partial class Budget
{
    public int Id { get; set; }

    public string Cliente { get; set; }

    public int FormaPago { get; set; }

    public DateTime Fecha { get; set; }

    public bool EstaActiva { get; set; }

    public virtual ICollection<BudgetDetail> DetallesFacturas { get; set; } = new List<BudgetDetail>();

    public virtual PayMethod FormaPagoNavigation { get; set; }
}