// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FacturacionAPI_EF.Models;

public partial class PayMethod
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public virtual ICollection<Budget> Facturas { get; set; } = new List<Budget>();
}